export const STATUSES = ['Действующая', 'На актуализации', 'Архивная'];

export const INITIAL_FUNCTIONS = [
  // === Направление 1: Жилищная инфраструктура (L1) ===
  {
    id: 'ЖИ-01',
    name: 'Формирование и реализация жилищной политики',
    description: 'Разработка и реализация мероприятий в рамках жилищной политики Фонда. Директор департамента.',
    result: 'Утверждённая жилищная политика',
    level: 1,
    directionId: 1,
    parentId: null,
    departmentId: 1,
    responsibleId: 1,
    bpmnXml: '__DEMO__',
    status: 'Действующая',
    createdAt: '2024-01-15T10:00:00.000Z',
    updatedAt: '2024-06-20T14:30:00.000Z',
    updatedBy: 12,
  },
  {
    id: 'ЖИ-02',
    name: 'Предоставление финансовой поддержки жилищных программ',
    description: 'Предоставление финансовой поддержки участникам жилищных программ.',
    result: 'Распределённые субсидии и гранты',
    level: 1,
    directionId: 1,
    parentId: null,
    departmentId: 2,
    responsibleId: 2,
    bpmnXml: null,
    status: 'Действующая',
    createdAt: '2024-01-15T10:00:00.000Z',
    updatedAt: '2024-05-10T09:00:00.000Z',
    updatedBy: 12,
  },
  {
    id: 'ЖИ-03',
    name: 'Мониторинг хода реализации жилищных программ',
    description: 'Мониторинг хода реализации жилищных программ.',
    result: 'Отчёты по мониторингу',
    level: 1,
    directionId: 1,
    parentId: null,
    departmentId: 3,
    responsibleId: 3,
    bpmnXml: null,
    status: 'На актуализации',
    createdAt: '2024-02-01T10:00:00.000Z',
    updatedAt: '2024-07-01T11:00:00.000Z',
    updatedBy: 12,
  },
  {
    id: 'ЖИ-04',
    name: 'Методологическое обеспечение жилищных программ',
    description: 'Разработка методических документов и стандартов жилищных программ.',
    result: 'Методические материалы',
    level: 1,
    directionId: 1,
    parentId: null,
    departmentId: 4,
    responsibleId: 4,
    bpmnXml: null,
    status: 'Действующая',
    createdAt: '2024-02-15T10:00:00.000Z',
    updatedAt: '2024-04-05T16:00:00.000Z',
    updatedBy: 12,
  },
  {
    id: 'ЖИ-05',
    name: 'Взаимодействие с органами власти',
    description: 'Взаимодействие с федеральными и региональными органами власти.',
    result: 'Заключённые соглашения',
    level: 1,
    directionId: 1,
    parentId: null,
    departmentId: 5,
    responsibleId: 5,
    bpmnXml: null,
    status: 'Действующая',
    createdAt: '2024-03-01T10:00:00.000Z',
    updatedAt: '2024-06-15T12:00:00.000Z',
    updatedBy: 12,
  },

  // === Направление 1: Жилищная инфраструктура (L2 для ЖИ-01) ===
  {
    id: 'ЖИ-01-01',
    name: 'Анализ потребностей в жилищном строительстве',
    description: 'Анализ потребностей в жилищном строительстве по регионам.',
    result: 'Аналитический отчёт',
    level: 2,
    directionId: 1,
    parentId: 'ЖИ-01',
    departmentId: 4,
    responsibleId: 2,
    bpmnXml: null,
    status: 'Действующая',
    createdAt: '2024-03-10T10:00:00.000Z',
    updatedAt: '2024-06-20T14:30:00.000Z',
    updatedBy: 12,
  },
  {
    id: 'ЖИ-01-02',
    name: 'Разработка жилищных программ',
    description: 'Формирование и корректировка жилищных программ.',
    result: 'Проект программы',
    level: 2,
    directionId: 1,
    parentId: 'ЖИ-01',
    departmentId: 4,
    responsibleId: 4,
    bpmnXml: null,
    status: 'Действующая',
    createdAt: '2024-03-10T10:00:00.000Z',
    updatedAt: '2024-05-15T08:00:00.000Z',
    updatedBy: 12,
  },
  {
    id: 'ЖИ-01-03',
    name: 'Согласование и утверждение программ',
    description: 'Согласование и утверждение жилищных программ с руководством.',
    result: 'Утверждённая программа',
    level: 2,
    directionId: 1,
    parentId: 'ЖИ-01',
    departmentId: 5,
    responsibleId: 9,
    bpmnXml: null,
    status: 'Действующая',
    createdAt: '2024-03-15T10:00:00.000Z',
    updatedAt: '2024-04-20T10:00:00.000Z',
    updatedBy: 12,
  },
  {
    id: 'ЖИ-01-04',
    name: 'Контроль реализации жилищных программ',
    description: 'Контроль реализации жилищных программ и достижения KPI.',
    result: 'Отчёт о контроле',
    level: 2,
    directionId: 1,
    parentId: 'ЖИ-01',
    departmentId: 3,
    responsibleId: 10,
    bpmnXml: null,
    status: 'На актуализации',
    createdAt: '2024-04-01T10:00:00.000Z',
    updatedAt: '2024-07-10T09:00:00.000Z',
    updatedBy: 12,
  },

  // === Направление 2: Коммунальная инфраструктура (L1) ===
  {
    id: 'КИ-01',
    name: 'Модернизация коммунальной инфраструктуры',
    description: 'Планирование и контроль модернизации объектов коммунальной инфраструктуры.',
    result: 'План модернизации',
    level: 1,
    directionId: 2,
    parentId: null,
    departmentId: 6,
    responsibleId: 6,
    bpmnXml: null,
    status: 'Действующая',
    createdAt: '2024-01-20T10:00:00.000Z',
    updatedAt: '2024-05-20T10:00:00.000Z',
    updatedBy: 12,
  },
  {
    id: 'КИ-02',
    name: 'Финансирование проектов коммунальной инфраструктуры',
    description: 'Управление финансированием проектов в сфере ЖКХ.',
    result: 'Распределённые средства',
    level: 1,
    directionId: 2,
    parentId: null,
    departmentId: 2,
    responsibleId: 2,
    bpmnXml: null,
    status: 'Действующая',
    createdAt: '2024-02-10T10:00:00.000Z',
    updatedAt: '2024-06-01T10:00:00.000Z',
    updatedBy: 12,
  },

  // === Направление 3: Дольщики (L1) ===
  {
    id: 'ДЛ-01',
    name: 'Восстановление прав обманутых дольщиков',
    description: 'Организация мероприятий по восстановлению прав граждан-участников долевого строительства.',
    result: 'Восстановленные права дольщиков',
    level: 1,
    directionId: 3,
    parentId: null,
    departmentId: 7,
    responsibleId: 7,
    bpmnXml: null,
    status: 'Действующая',
    createdAt: '2024-01-25T10:00:00.000Z',
    updatedAt: '2024-04-15T10:00:00.000Z',
    updatedBy: 12,
  },
  {
    id: 'ДЛ-02',
    name: 'Мониторинг проблемных объектов',
    description: 'Ведение реестра и мониторинг проблемных объектов долевого строительства.',
    result: 'Актуальный реестр объектов',
    level: 1,
    directionId: 3,
    parentId: null,
    departmentId: 7,
    responsibleId: 7,
    bpmnXml: null,
    status: 'Действующая',
    createdAt: '2024-02-05T10:00:00.000Z',
    updatedAt: '2024-05-20T10:00:00.000Z',
    updatedBy: 12,
  },

  // === Направление 4: Восстановление воссоединённых регионов (L1) ===
  {
    id: 'ВР-01',
    name: 'Восстановление жилищного фонда',
    description: 'Организация восстановления жилищного фонда в воссоединённых регионах.',
    result: 'Восстановленные жилые объекты',
    level: 1,
    directionId: 4,
    parentId: null,
    departmentId: 8,
    responsibleId: 8,
    bpmnXml: null,
    status: 'Действующая',
    createdAt: '2024-03-01T10:00:00.000Z',
    updatedAt: '2024-06-10T10:00:00.000Z',
    updatedBy: 12,
  },

  // === Направление 5: СЭЗ и Управление имуществом (L1) ===
  {
    id: 'СЭЗ-01',
    name: 'Управление объектами в особых экономических зонах',
    description: 'Управление и контроль объектов недвижимости в СЭЗ.',
    result: 'Актуализированный реестр объектов',
    level: 1,
    directionId: 5,
    parentId: null,
    departmentId: 9,
    responsibleId: 9,
    bpmnXml: null,
    status: 'Действующая',
    createdAt: '2024-01-10T10:00:00.000Z',
    updatedAt: '2024-04-30T10:00:00.000Z',
    updatedBy: 12,
  },

  // === Направление 6: Развитие территорий (L1) ===
  {
    id: 'РТ-01',
    name: 'Планирование развития территорий',
    description: 'Формирование планов комплексного развития территорий.',
    result: 'Планы развития',
    level: 1,
    directionId: 6,
    parentId: null,
    departmentId: 10,
    responsibleId: 10,
    bpmnXml: null,
    status: 'Действующая',
    createdAt: '2024-02-20T10:00:00.000Z',
    updatedAt: '2024-05-25T10:00:00.000Z',
    updatedBy: 12,
  },

  // === Направление 7: Сервисные направления (L1) ===
  {
    id: 'СН-01',
    name: 'ИТ-обеспечение деятельности Фонда',
    description: 'Обеспечение информационно-технологической инфраструктуры Фонда.',
    result: 'Бесперебойная работа ИТ-систем',
    level: 1,
    directionId: 7,
    parentId: null,
    departmentId: 11,
    responsibleId: 11,
    bpmnXml: null,
    status: 'Действующая',
    createdAt: '2024-01-05T10:00:00.000Z',
    updatedAt: '2024-03-15T10:00:00.000Z',
    updatedBy: 12,
  },
  {
    id: 'СН-02',
    name: 'Кадровое обеспечение',
    description: 'Управление персоналом и кадровое делопроизводство.',
    result: 'Укомплектованный штат',
    level: 1,
    directionId: 7,
    parentId: null,
    departmentId: 12,
    responsibleId: 12,
    bpmnXml: null,
    status: 'Действующая',
    createdAt: '2024-01-05T10:00:00.000Z',
    updatedAt: '2024-02-28T10:00:00.000Z',
    updatedBy: 12,
  },
];
